version: '2.2'

# 参考：https://www.elastic.co/guide/en/elastic-stack-get-started/7.5/get-started-docker.html
# 网络：elk-net（172.31.0.1，下面节点全部分配静态IP）
# logstash（172.31.0.21）
#   tcp input端口-映射宿主机端口：4561-4569:4561-4569
# elasticsearch(3个节点，172.31.0.31，172.31.0.32，172.31.0.33)
#   内部服务端口：9200
#   映射宿主机端口: 9201 9202 9203
# elasticsearch-head（172.31.0.34）
#   外部映射端口: 9101
# kibana（172.31.0.41）
#   内部服务端口-映射宿主机端口：5601：5602

services:

  #logstash
  lgs01:
    image: ${LOGSTASH_IMAGE}
    container_name: lgs01
    volumes:
      - ${LGS01_CONFIG_PATH}:/usr/share/logstash/config
      - ${LGS01_PIPELINE_PATH}:/usr/share/logstash/pipeline
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://172.31.0.31:9200,http://172.31.0.32:9202,http://172.31.0.33:9203
    ports:
      #预留作为input端口
      - 4561-4569:4561-4569
    networks:
      elk-net:
        ipv4_address: 172.31.0.21

  #elasticsearch
  es01:
    image: ${ES_IMAGE}
    container_name: es01
    # 不建议在environment中设置，最好在配置文件elasticsearch.yml中配置
    environment:
      - node.name=es01
      #- cluster.name=monitor-es-docker-cluster
      - discovery.seed_hosts=172.31.0.32,172.31.0.33
      - cluster.initial_master_nodes=es01,es02,es03
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES01_CONFIG_PATH}:/usr/share/elasticsearch/config
      - ${ES01_DATA_PATH}:/usr/share/elasticsearch/data
      - ${ES01_LOGS_PATH}:/usr/share/elasticsearch/logs
    ports:
      - 9201:9200
    networks:
      elk-net:
        ipv4_address: 172.31.0.31

  es02:
    image: ${ES_IMAGE}
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=172.31.0.31,172.31.0.33
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES02_CONFIG_PATH}:/usr/share/elasticsearch/config
      - ${ES02_DATA_PATH}:/usr/share/elasticsearch/data
      - ${ES02_LOGS_PATH}:/usr/share/elasticsearch/logs
    ports:
      - 9202:9200
    networks:
      elk-net:
        ipv4_address: 172.31.0.32

  es03:
    image: ${ES_IMAGE}
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=172.31.0.31,172.31.0.32
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES03_CONFIG_PATH}:/usr/share/elasticsearch/config
      - ${ES03_DATA_PATH}:/usr/share/elasticsearch/data
      - ${ES03_LOGS_PATH}:/usr/share/elasticsearch/logs
    ports:
      - 9203:9200
    networks:
      elk-net:
        ipv4_address: 172.31.0.33

  #elasticsearch-head
  #注意es-head官方镜像(即 mobz/elasticsearch-head)有个bug(没有设置content-type: application/json)
  es-head:
    image: ${ES_HEAD_IMAGE}
    container_name: es-head
    ports:
      - 9101:9100
    networks:
      elk-net:
        ipv4_address: 172.31.0.34

  kib01:
    image: kibana:7.5.1
    container_name: kib01
    ports:
      - 5602:5601
    volumes:
      - ${KIB01_CONFIG_PATH}:/usr/share/kibana/config
#    environment:
#      - SERVER_NAME=kib01
#      - ELASTICSEARCH_HOSTS=http://172.31.0.31:9200
    networks:
      elk-net:
        ipv4_address: 172.31.0.41

networks:
  elk-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
